=== ICampos0007/Online_Shop/src/main/resources/ShippingMethods.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:complexType name="UserType">
        <xs:all>
            <xs:element name="username" type="xs:string"/>
            <xs:element name="passw" type="xs:string"/>
            <xs:element name="email" type="xs:string"/>


        </xs:all>
        <xs:attribute name="id" type="xs:int" use="required"/>
    </xs:complexType>

    <xs:complexType name="UsersType">
        <xs:sequence>
            <xs:element name="user" type="UserType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="OrderType">
        <xs:all>
            <xs:element name="users" type="UsersType"/>
            <xs:element name="order_date" type="xs:dateTime"/>
            <xs:element name="total_price" type="xs:double"/>
        </xs:all>
        <xs:attribute name="id" type="xs:int" use="required"/>
    </xs:complexType>

    <xs:complexType name="OrdersType">
        <xs:sequence>
            <xs:element name="order" type="OrderType" minOccurs="0" maxOccurs="unbounded">

            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="ShippingMethodsType">
        <xs:all>
            <xs:element name="orders" type="OrdersType"/>
            <xs:element name="shipping_method_name" type="xs:string"/>
            <xs:element name="shipping_cost" type="xs:double"/>
            <xs:element name="order_id" type="xs:int"/>
        </xs:all>
    </xs:complexType>
    <xs:element name="ShippingMethods" type="ShippingMethodsType">

    </xs:element>
</xs:schema>

=== ICampos0007/Online_Shop/src/main/resources/ShippingMethods.xml
<ShippingMethods xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ShippingMethods.xsd">
        <shipping_method_name>A1 shipping</shipping_method_name>
        <shipping_cost>30</shipping_cost>
        <order_id>1</order_id>
        <orders>
            <order id="1">
                <order_date>2024-01-03T11:33:45</order_date>
                <total_price>500</total_price>
                <users>
                    <user id="1">
                        <username>Jaymee</username>
                        <passw>abcd</passw>
                        <email>jaymee@gmail.com</email>
                    </user>
                </users>
            </order>
            <order id="2">
                <order_date>2024-01-02T06:23:54</order_date>
                <total_price>1000</total_price>
                <users>
                    <user id="6">
                        <username>Leon</username>
                        <passw>abc</passw>
                        <email>leon@gmail.com</email>
                    </user>
                </users>
            </order>
        </orders>
</ShippingMethods>
